### ISSUE TITLE
Seen boot-kotlinc?

### ISSUE THREAD

**Issue by seancorfield** [artemyarulin/clojure-kotlin#1]
Your repo got picked up by The REPL newsletter (congrats!) so I wondered if you'd seen my [boot-kotlinc](https://github.com/seancorfield/boot-kotlinc) project? I haven't touched it for ages but if it's at all useful -- or you have any suggestions for improvement! -- let me know. Maybe I could set it up to be runnable from `clj` if that seems useful.

**Comment by artemyarulin** [comment]
Hi, ha, thanks. Yeah, I've seen that one, I'm not familiar with boot, so decided to try clj and gradle. Actually thanks for the suggestion - I'll add it to the README :)
